
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlruns
    volumes:
      - ./mlflow:/mlruns         # artifacts + runs
      - ./mlflow_db:/mlflow_db   # (optional) if you later use file-based DB path
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
    restart: unless-stopped
